#!/bin/bash

# Install and enable Jupyter nbextensions
# https://github.com/binder-examples/jupyter-extension
jupyter contrib nbextension install --user
jupyter nbextension install toc2/main
jupyter nbextension install exercise2/main
jupyter nbextension enable toc2/main
jupyter nbextension enable qexercise2/main

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png